### ISSUE TITLE
no work in forge

### ISSUE THREAD

**Issue by TheVirusNVGM** [Natanaelel/re_search#1]
Hello, I’m very interested in your mod, but the problem is that it doesn’t work on Forge, or rather, it doesn’t show up in the list of mods

**Comment by Natanaelel** [comment]
This is a fabric mod. It wont work on forge.

**Comment by EvanHsieh0415** [comment]
> This is a fabric mod. It wont work on forge.

but you upload a forge version on curseforge:
https://www.curseforge.com/minecraft/mc-mods/regex-search/files/4746497

**Comment by Natanaelel** [comment]
Oh, lemme fix that rq. Thanks.
